xcopy /Y "C:\Workspace\CMP\Main\Source\SharedProjects\DataProviders\AbstractSqlProvider.cs" 
xcopy /Y "C:\Workspace\CMP\Main\Source\SharedProjects\Utilities\Config\GridUtil.cs"
xcopy /Y "C:\Workspace\CMP\Main\Source\UnitTest\Web\Controllers\AandD\JDBControllerTest.cs"
xcopy /Y "C:\Workspace\CMP\Main\Source\UnitTest\App.Config"
xcopy /Y "C:\Workspace\CMP\Main\Source\Web\Models\Configuration\ControlConfig.cs"
xcopy /Y "C:\Workspace\CMP\Main\Source\Web\Models\Chart.cs"
xcopy /Y "C:\Workspace\CMP\Main\Source\Web\UI\Controllers\ChartPageController.cs"
xcopy /Y "C:\Workspace\CMP\Main\Source\Web\Models\Chart.cs"
xcopy /Y "C:\Workspace\CMP\Main\Source\Web\Services\ChartService.cs"
 