//-------------------------------------------------------
Highcharts.Renderer.prototype.symbols.line = function(x, y, width, height) {
    return ['M',x,y,'L',x+height,y];
};
//-------------------------------------------------------
var chart = new Highcharts.Chart({
    chart:{
        renderTo:'container',
        type:'bar',
    },
    credits:{enabled:false},
    exporting:{enabled:false},
    title:{text:''},
    xAxis:{
        tickLength:0,
        lineColor:'#999',
        labels: {
            style: {
                fontWeight:'bold'
            }
        },
        lineWidth:0,
        categories:['Measure 1','Measure 2','Measure 3','Measure 4','Measure 5']
    },
    yAxis:{
        allowDecimals:false,
        tickColor:'#ccc',
        tickWidth:1,
        tickLength:3,
        lineWidth:1,
        lineColor:'#ccc',
        gridLineWidth:1,
        gridLineColor:'rgba(255,255,255,.25)',
        endOnTick:true,
        title:{text: ''},
        gridZIndex:4,
        min:-1,
        max:11,
        endOnTick:false,
        startOnTick:false,
     },
    legend:{enabled:false},
    plotOptions:{
        bar:{
            color:'rgba(90,155,212,.5)',
            //color:'rgba(156,156,156,.5)',
            shadow:false,
            borderWidth:1,
            borderColor:'rgba(24,90,169,.75)',
            borderRadius:3,
            pointWidth:14,
        },
        scatter:{
            marker:{
                symbol:'line',
                lineWidth:3,
                radius:9,
                lineColor:'#333'
            }
        }
    },
     series:[{
        data:[
            {y:10,low:0},
            {y:10,low:0},
            {y:10,low:0},
            {y:10,low:0},
            {y:10,low:0}
        ]
    },{
        type:'scatter',
        data:[
            {y:5,lineColor:'red'},
            {y:8,lineColor:'blue'},
            {y:9,lineColor:'green'},
            {y:7,lineColor:'yellow'},
            {y:4,lineColor:'orange'}
        ]
    }]
});